# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'

target 'PixabayImageApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for PixabayImageApp
  pod 'SDWebImage'

  target 'PixabayImageAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PixabayImageAppUITests' do
    # Pods for testing
  end

end
